#pragma config(Sensor, S1,     Test,           sensorHiTechnicTouchMux)
#pragma config(Motor,  motorA,          Left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Proximity,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AdvancedSensors.c"

task main ()
{
	int nButtonsMask;
	SensorType[S4] = sensorHiTechnicTouchMux;
	SensorType[S1] = sensorI2CHiTechnicColor;
	SensorType[S3] = sensorI2CHiTechnicColor;
	int rightRed;
	int rightGreen;
	int rightBlue;
	int leftRed;
	int leftGreen;
	int leftBlue;

	while(true){


//
// The sensor value is a 4-bit map indicating which of the possible four
// touch sensors are pressed.
//
		getRGB(S1, rightRed, rightGreen, rightBlue);
		getRGB(S3, leftRed, leftGreen, leftBlue);
		nButtonsMask = SensorValue[S4];
		if((nButtonsMask & 0x08)||leftRed > 20){
  		motor[Left] = 0;
  		motor[Right] = 0;
  		if(rightBlue > 20&&leftRed>20){
  			PlayTone(784, 15);
  		}
  	}
  	else{
  		motor[Left] = 50;
  		motor[Right] = 50;
  	}
	}
	motor[Left] = 0;
  motor[Right] = 0;



}

/*
* $Id: hitechnic-irseeker-v2-test1.c 109 2012-09-25 17:10:26Z xander $
*/
