#pragma config(Sensor, S4,     MultiPlex,           sensorHiTechnicTouchMux)
#pragma config(Sensor, S1,     rightColor,           sensorI2CHiTechnicColor)
#pragma config(Sensor, S3,     leftColor,           sensorI2CHiTechnicColor)
#pragma config(Motor,  motorA,          Left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Proximity,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AdvancedSensors.c"
void seek(){
	int rightRed;
	int rightGreen;
	int rightBlue;
	int leftRed;
	int leftGreen;
	int leftBlue;
	while(leftRed < 20){
		getRGB(rightColor, rightRed, rightGreen, rightBlue);
		getRGB(leftColor, leftRed, leftGreen, leftBlue);
		nButtonsMask = SensorValue[MultiPlex];
		if((nButtonsMask & 0x08)||leftRed > 20){
	  		motor[Left] = 0;
	  		motor[Right] = 0;
	  		if(rightBlue > 20&&leftRed>20){
	  			PlayTone(784, 15);
	  		}
  		}
	  	else{
	  		motor[Left] = 50;
	  		motor[Right] = 50;
	  	}
	}
	motor[Left] = 0;
  	motor[Right] = 0;
}

void sensorLeft(){
	while(!(nButtonsMask & 0x01)){
		nButtonsMask = SensorValue[MultiPlex];
		motor[Proximity] = 20;
	}
	motor[Proximity] = -20;
	//Wait
	//Stpp
	motor[Proximity] = 0;
}
void sensorRight(){
	while(!(nButtonsMask & 0x02)){
		nButtonsMask = SensorValue[MultiPlex];
		motor[Proximity] = -20;
	}
	motor[Proximity] = 20;
	//Wait
	//Stpp
	motor[Proximity] = 0;

}

void sense(){
	if(sensorLeft() > sensorRight()){
		//Lets go left
		
	}
	else{

	}
	
}

task main ()
{
	int num = 0;
	while(num != 4){
		seek();

	}


}

/*
* $Id: hitechnic-irseeker-v2-test1.c 109 2012-09-25 17:10:26Z xander $
*/
