#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Sensor, S3,     Sonar,          sensorSONAR)
#pragma config(Sensor, S4,     sideTouch,      sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     Shoulder,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     Lift,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     Spin,          tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     driveFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     driveFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_1,     driveR,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     driveL,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: hitechnic-irseeker-v2-test2.c 133 2013-03-10 15:15:38Z xander $
 */

/**
 * hitechnic-irseeker-v2.h provides an API for the HiTechnic IR Seeker V2.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 *
 * Credits:
 * - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.59 AND HIGHER.

 * Xander Soldaat (xander_at_botbench.com)
 * Dick Swan
 * Gus Jansson
 * 04 October 2012
 * version 0.1
 */

#include "drivers/hitechnic-irseeker-v2.h"

// global variables
long nNumbCyles;
long nInits = 0;
string sTextLines[8];
#include "drivers/hitechnic-gyro.h"
// function prototypes
void displayText(int nLineNumber, const string cChar, int nValueDC, int nValueAC);
void displayText3(int nLineNumber, const string cChar, int nValueDC, int nValueAC, int nValueEnh);
void displayInstructions();
	bool directional = true;
// main task

	void stopMotors(){
			motor[driveL] = 0;
				  motor[driveFL] = 0;
				  motor[driveR] = 0;
				  motor[driveFR] = 0;
     // motor[Shoulder] = 25;

}
int set = 1;
int sticky = 1000;
task driveToRamp(){
	nxtDisplayClearTextLine(2);
	nxtDisplayClearTextLine(3);

	motor[driveL] = -30;
  motor[driveFL] = -30;
  motor[driveR] = -30;
  motor[driveFR] = -30;
  wait1Msec(1000);


  motor[driveL] = 30;
  motor[driveFL] = 30;
  motor[driveR] = -30;
  motor[driveFR] = -30;
  wait1Msec(2000);

  motor[driveL] = 100;
  motor[driveFL] = 100;
  motor[driveR] = 100;
  motor[driveFR] = 100;
  wait1Msec(200);

   motor[driveL] = 30;
  motor[driveFL] = 30;
  motor[driveR] = -30;
  motor[driveFR] = -30;
  wait1Msec(200);

  motor[driveL] = 100;
  motor[driveFL] = 100;
  motor[driveR] = 100;
  motor[driveFR] = 100;
  wait1Msec(1300);
	 float rotSpeed = 0;
  float heading = 0;

  // Calibrate the gyro, make sure you hold the sensor still
  HTGYROstartCal(HTGYRO);

  // Reset the timer.
  time1[T1] = 0;

  while (true)
  {
    // Wait until 20ms has passed
    while (time1[T1] < 20)
      wait1Msec(1);

    // Reset the timer
    time1[T1]=0;

    // Read the current rotation speed
    rotSpeed = HTGYROreadRot(HTGYRO);

    // Calculate the new heading by adding the amount of degrees
    // we've turned in the last 20ms
    // If our current rate of rotation is 100 degrees/second,
    // then we will have turned 100 * (20/1000) = 2 degrees since
    // the last time we measured.
    heading += rotSpeed * 0.02;

    // Display our current heading on the screen
    nxtDisplayCenteredBigTextLine(3, "%2.0f", heading);
  }
  motor[driveL] = -100;
  motor[driveFL] = 100;
  motor[driveR] = 100;
  motor[driveFR] = -100;
  wait1Msec(500);


  motor[Shoulder]=-40;
  wait1Msec(300);
  motor[Shoulder]=15;

  motor[driveL] = -100;
  motor[driveFL] = -100;
  motor[driveR] = -100;
  motor[driveFR] = -100;
  wait1Msec(2000);

	stopMotors();
	StopTask(driveToRamp);
}
task moveDump(){
	while(true){
		motor[driveL] = 100;
		motor[driveFL] = 100;
		motor[driveR] = 100;
		motor[driveFR] = 100;
		SensorType[Sonar] = sensorSONAR;
		int nValue = SensorValue[Sonar];
		while(nValue>31||nValue==255){
			nValue = SensorValue[Sonar];
		}
			stopMotors();
			wait1Msec(200);
		motor[driveL] = 40;
			 motor[driveFL] = 40;
				  motor[driveR] = -40;
				  motor[driveFR] = -40;
				  wait1Msec(200);
		stopMotors();
		wait1Msec(500);
		motor[Spin] = -100;
		wait1Msec(1000);
		motor[Spin] = 0;
		StartTask(driveToRamp);
		StopTask(moveDump);

	}
}
task shoulderSticky(){
	while(true){
		if(nMotorEncoder[Shoulder]<sticky){
			motor[Shoulder]=100;
		}
		else{
			motor[Shoulder]=15;
			wait1Msec(200);
			StartTask(moveDump);
			StopTask(shoulderSticky);
		}
		wait1Msec(100);
	}
}
	int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
	int acS1, acS2, acS3, acS4, acS5 = 0;

task Seek(){
	ClearTimer(T1);
	while(true){
		HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5 );
	 	if(abs(acS5-acS4)<30&&acS5+acS4>70){
	 				if(time100[T1] > 10) set = 2;

      			nxtDisplayClearTextLine(2);
      		nxtDisplayString(2,"Ahead");
      		wait1Msec(0);

      		 PlaySound(soundBeepBeep);
      		StartTask(shoulderSticky);
      		stopMotors();
      		StopTask(Seek);
      	}
      	else{
      		nxtDisplayClearTextLine(2);
      		nxtDisplayString(2,"No");
      		motor[driveL] = -40;
				  motor[driveFL] = -40;
				  motor[driveR] = 40;
				  motor[driveFR] = 40;
      	}
     }
}
task main ()
{

  int _dirDC = 0;
  int _dirAC = 0;

	int _dirEnh, _strEnh;

	// the default DSP mode is 1200 Hz.
  tHTIRS2DSPMode _mode = DSP_1200;

  // show the user what to do
  displayInstructions();
  	StartTask(Seek);
  while(true)
  {
    // You can switch between the two different DSP modes by pressing the
    // orange enter button


    while(bSoundActive)
    {}
    eraseDisplay();
    nNumbCyles = 0;
    ++nInits;
    while (true)
    {
      if ((nNumbCyles & 0x04) == 0)
        nxtDisplayTextLine(0, "Initializing...");
      else
        nxtDisplayTextLine(0, "");
      nxtDisplayCenteredBigTextLine(1, "IR Seekr");

      // set the DSP to the new mode
      if (HTIRS2setDSPMode(HTIRS2, _mode))
        break; // Sensor initialized

      ++nNumbCyles;
      PlaySound(soundShortBlip);
      nxtDisplayTextLine(4, "Inits: %d / %d", nInits, nNumbCyles);
      nxtDisplayCenteredTextLine(6, "Connect Sensor");
      nxtDisplayCenteredTextLine(7, "to Port S1");
      wait1Msec(100);
    }

    eraseDisplay();
    for (int i = 0; i < 8; ++i)
      sTextLines[i] = "";

    // display the current DSP mode
    if (_mode == DSP_1200)
      nxtDisplayTextLine(0, "    DC 1200");
    else
      nxtDisplayTextLine(0, "    DC  600");

    while (true)
    {
      ++nNumbCyles;
      if (nNxtButtonPressed == kEnterButton)
      {
        // "Enter" button has been pressed. Need to switch mode

        _mode = (_mode == DSP_1200) ?  DSP_600 : DSP_1200;
        while(nNxtButtonPressed == kEnterButton)
        {
          // Wait for "Enter" button release
        }
        break;
      }
      if (nNxtButtonPressed == kRightButton)
      {
        // "Enter" button has been pressed. Need to switch mode

        directional = !directional;
        while(nNxtButtonPressed == kEnterButton)
        {
          // Wait for "Enter" button release
        }
        break;
      }

      // Read the current non modulated signal direction
      _dirDC = HTIRS2readDCDir(HTIRS2);
      if (_dirDC < 0)
        break; // I2C read error occurred

      // read the current modulated signal direction
      _dirAC = HTIRS2readACDir(HTIRS2);
      if (_dirAC < 0)
        break; // I2C read error occurred

      // Read the individual signal strengths of the internal sensors
      // Do this for both unmodulated (DC) and modulated signals (AC)
      if (!HTIRS2readAllDCStrength(HTIRS2, dcS1, dcS2, dcS3, dcS4, dcS5))
        break; // I2C read error occurred
      if (!HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5 ))
        break; // I2C read error occurred

      // Read the Enhanced direction and strength
			if (!HTIRS2readEnhanced(HTIRS2, _dirEnh, _strEnh))
        break; // I2C read error occurred

			if(!directional){
      displayText3(1, "D", _dirDC, _dirAC, _dirEnh);
      displayText(2, "1", dcS1, acS1);
      displayText(3, "2", dcS2, acS2);
      displayText3(4, "3", dcS3, acS3, _strEnh);
      displayText(5, "4", dcS4, acS4);
      displayText(6, "5", dcS5, acS5);
    	}
      else if(directional){

      	//nxtDisplayBigStringAt(20,45,"Done");
      	/*if(acS1>40){

      		motor[driveL] = -30;
				  motor[driveFL] = -30;
				  motor[driveR] = 30;
				  motor[driveFR] = 30;
      		nxtDisplayBigStringAt(20,45,"On Left");

      	}
      	else if(acS5>40){
      			motor[driveL] = 30;
				  motor[driveFL] = 30;
				  motor[driveR] = -30;
				  motor[driveFR] = -30;
      	 	nxtDisplayBigStringAt(20,45,"On Right");
      	}
      	else if(acS3>50){
      		stopMotors();
      		nxtDisplayBigStringAt(20,45,"Ahead");
      	}
      	else{
	      	motor[driveL] = -30;
				  motor[driveFL] = -30;
				  motor[driveR] = 30;
				  motor[driveFR] = 30;
      	}
      	*/


    	}
      nxtDisplayTextLine(7, "Enter to switch");
    }
  }
}

// Display the instructions to the user
void displayInstructions()
{
  nxtDisplayCenteredTextLine(0, "HiTechnic");
  nxtDisplayCenteredBigTextLine(1, "IR Seekr");
  nxtDisplayCenteredTextLine(3, "Test 1");
  nxtDisplayCenteredTextLine(5, "Press enter to");
  nxtDisplayCenteredTextLine(6, "switch between");
  nxtDisplayCenteredTextLine(7, "600 and 1200 Hz");
  wait1Msec(2000);
}

// Minimize LCD screen flicker by only updating LCD when data has changed
void displayText(int nLineNumber, const string cChar, int nValueDC, int nValueAC)
{
	if(!directional){
  string sTemp;

	StringFormat(sTemp, "%4d %4d", nValueDC, nValueAC);

  // Check if the new line is the same as the previous one
  // Only update screen if it's different.
  if (sTemp != sTextLines[nLineNumber])
  {
    string sTemp2;

    sTextLines[nLineNumber] = sTemp;
    StringFormat(sTemp2, "%s:%s", cChar, sTemp);
    nxtDisplayTextLine(nLineNumber, sTemp2);
  }
	}
}

// Minimize LCD screen flicker by only updating LCD when data has changed
void displayText3(int nLineNumber, const string cChar, int nValueDC, int nValueAC, int nValueEnh)
{
	if(!directional){
  string sTemp;

  StringFormat(sTemp, "%4d %4d %3d", nValueDC, nValueAC, nValueEnh);

  // Check if the new line is the same as the previous one
  // Only update screen if it's different.
  if (sTemp != sTextLines[nLineNumber])
  {
    string sTemp2;

    sTextLines[nLineNumber] = sTemp;
    StringFormat(sTemp2, "%s:%s", cChar, sTemp);
    nxtDisplayTextLine(nLineNumber, sTemp2);
  }
	}
}

/*
 * $Id: hitechnic-irseeker-v2-test2.c 133 2013-03-10 15:15:38Z xander $
 */
