#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     liftheight,     sensorI2CHiTechnicColor)
#pragma config(Motor,  mtr_S1_C1_1,     ShoulderR,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     ShoulderL,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     driveR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     driveL,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C2_1,    pullreleaseR,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    pullreleaseL,         tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    armreleaseR,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_4,    armreleaseL,          tServoStandard)
#pragma config(Servo,  srvo_S1_C2_5,    wrist,                tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    hand,                 tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AdvancedSensors.c"

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  mtr_S1_C4_1,    Collecter,            tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.
	int wristLoc = 125;
	int tick = 0;
task main(){

	//1const int THRESHOLD = 5;
	getJoystickSettings (joystick);

	//bool turbo = false;
	//
	//waitForStart();   // wait for start of tele-op phase
	//servo[armRelease] = 0;

	//servo[binlift] = 30;
	//const tSensors kColorSensorPort   = S2;	// We want the color sensor to be on port "S2"
	int sto;

  //SensorType[kColorSensorPort] = sensorI2CHiTechnicColor; // Configure the sensor

  //Initial Setup


  /*
 		Setup arm at correct angles
  */
  while(SensorValue(S2) != 1)
  {
  	motor[ShoulderR] = 	motor[ShoulderL] = 1; //Slowly lower.
  }
  motor[ShoulderR] = 	motor[ShoulderL] = 10; //Actually stops.
  nMotorEncoder[ShoulderR]= motor[ShoulderL] = 0; //We are now at "0"


	while(true)
	{
				servo[armreleaseL] = servo[armreleaseR] = 128;
				if(joy1Btn(02)){
					servo[hand] = 255;
					servo[hand] = 0;
				}
				if(joy1Btn(03)){
					servo[hand] = 0;
					servo[hand] = 255;
				}
				if(joy1Btn(06)&&nMotorEncoder[ShoulderR]<500){
					motor[ShoulderR] = 	motor[ShoulderL] = 80;
					sto = false;
				}

				else if(joy1Btn(08)&&nMotorEncoder[ShoulderR]>150){
					sto = false;
					motor[ShoulderR] = 	motor[ShoulderL] = 1;
				}
				else{
					if(sto == false){
				 		motor[ShoulderR] = 	motor[ShoulderL] = 50;
				 		sto = true;
				 	}
				 	motor[ShoulderR] = 	motor[ShoulderL] = 20;
		 	  }
		 	  tick++;
				if(joy1Btn(05)){
					if(wristLoc>50&&tick>30){
						tick=0;
						wristLoc--;
					}
				}
				if(joy1Btn(07)){
					if(wristLoc<150&&tick>30){
						tick=0;
						wristLoc++;
					}
				}


					servo[wrist] = wristLoc;







       	float onex = joystick.joy1_x1;
       	float oney = joystick.joy1_y1;
       	float twox = joystick.joy1_x2;
       	float twoy = joystick.joy1_y2;
       	if(abs(onex)<20)onex=0;
       	if(abs(oney)<20)oney=0;
       	if(abs(twox)<20)twox=0;
       	if(abs(twoy)<20)twoy=0;
       	int left;
       	int right;

       	left = -oney;
       	right = -oney;

       	left+=twox;
       	right-=twox;



       	motor[driveL] = left;

       	motor[driveR] = right;









          //servo[binlift2] = bin;
  	}
}
