#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     DFL,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     DBL,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     arm,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     DBR,           tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     DFR,           tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C4_1,    armRelease,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    extension1,           tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    binlift,              tServoStandard)
#pragma config(Servo,  srvo_S1_C4_4,    binlift2,             tServoStandard)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  mtr_S1_C4_1,    Collecter,            tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

task main(){
	//1const int THRESHOLD = 5;
	getJoystickSettings (joystick);

	//bool turbo = false;
	waitForStart();   // wait for start of tele-op phase
	servo[armRelease] = 0;
	int tick = 0;
	int bin = 255;
	//servo[binlift] = 30;
	while(true)
	{
		tick++;
		/*if (joy1Btn(7)) {
			turbo = !turbo;
		}*/
      	/*motor[DFR] =  ((joystick.joy1_y1) - (joystick.joy1_x1) - (joystick.joy1_x2));
       	motor[DFL] = (-(joystick.joy1_y1) - (joystick.joy1_x1) - (joystick.joy1_x2))/2;
       	motor[DBR] = ((joystick.joy1_y1) + (joystick.joy1_x1) - (joystick.joy1_x2))/2;
       	motor[DBL] =  (-(joystick.joy1_y1) + (joystick.joy1_x1) - (joystick.joy1_x2))/2;/**/

       	float onex = joystick.joy1_x1;
       	float oney = joystick.joy1_y1;
       	float twox = joystick.joy1_x2;
       	float twoy = joystick.joy1_y2;

       	onex = ((onex/120)*(onex/120)*(onex/120))*128;
       	oney = ((oney/120)*(oney/120)*(oney/120))*128;
       	twox = ((twox/120)*(twox/120)*(twox/120))*128;
       	twoy = ((twoy/120)*(twoy/120)*(twoy/120))*128;


       	if(abs(onex)<6)onex=0;

       	if(abs(oney)<6)oney=0;


       	if(abs(twox)<16)twox=0;

       	if(abs(twoy)<16)twoy=0;

       	motor[DFR] = (oney - onex - twox)/2;
       	motor[DFL] = (-oney - onex - twox)/2;
       	motor[DBR] = (oney + onex - twox)/2;
       	motor[DBL] = (-oney + onex - twox)/2;

					int speed = 0;

					if (joy1Btn(1))
          {
          	//int escape = 0;
          	servo[binlift2] = 139;
          	servo[binlift] = 139;
          	bin = 139;
          	//motor[arm] = -50;
          	//wait1Msec(200);
          	//motor[arm]= 0;
          }
          if (joy1Btn(3))
          {
          	servo[binlift] = 139;
          	bin = 139;
          	motor[arm] = -80;
          	motor[DFL] = 50;
          	motor[DFR] = -50;
          	motor[DBL] = 50;
          	motor[DBR] = -50;
          	wait1Msec(200);
          	motor[arm]= 0;
          	wait10Msec(100);
          	motor[DFL] = 0;
          	motor[DFR] = 0;
          	motor[DBL] = 0;
          	motor[DBR] = 0;

          }


          if (joy1Btn(8))
          {
              speed = 100;
          }
          else if (joy1Btn(6))
          {
              speed = -100;
          }
          motor[arm] = speed;

          //servo[binlift] = 0;
          if(tick > 20){
	          if (joy1Btn(5))
	          {

	          	bin--;

	          }
	          else if (joy1Btn(7))
	          {
	          	bin++;
	          }
	          if(bin>200) bin = 200;
	          if(bin<30) bin = 30;
	          tick=0;
        	}
        	nxtDisplayTextLine(0,"This is one %d",bin);
          servo[binlift] = bin;
          servo[binlift2] = bin;
  	}
}
