#pragma config(Sensor, S1,     rightColor,     sensorI2CHiTechnicColor)
#pragma config(Sensor, S2,     sonar,          sensorSONAR)
#pragma config(Sensor, S3,     leftColor,      sensorI2CHiTechnicColor)
#pragma config(Sensor, S4,     MultiPlex,      sensorHiTechnicTouchMux)
#pragma config(Motor,  motorA,          Left,          tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          Right,         tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          Proximity,     tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "AdvancedSensors.c"
void seek(){
	int rightRed;
	int rightGreen;
	int rightBlue;
	int leftRed;
	int leftGreen;
	int leftBlue;
	int escape = 0;
	while(escape == 0){
		getRGB(rightColor, rightRed, rightGreen, rightBlue);
		getRGB(leftColor, leftRed, leftGreen, leftBlue);
		int nButtonsMask = SensorValue[MultiPlex];
		if(leftBlue>20||leftRed > 20){
	  		motor[Left] = 0;
	  		motor[Right] = 0;
	  		if((rightBlue > 20&&leftRed>20)||(rightRed > 20&&leftBlue>20)){
	  			PlayTone(784, 15);
	  			escape = 1;
	  		}
  		}
	  	else{
	  		motor[Left] = 40;
	  		motor[Right] = 40;
	  	}
	}
	motor[Left] = 0;
  	motor[Right] = 0;
}

int sensorLeft(){
	int nButtonsMask = SensorValue[MultiPlex];
	while(!(nButtonsMask & 0x01)){
		nButtonsMask = SensorValue[MultiPlex];
		motor[Proximity] = 20;
	}
	motor[Proximity] = -20;
	//Wait
	wait1Msec(1000);
	//Stpp
	motor[Proximity] = 0;
	return SensorValue(sonar);
}
int sensorRight(){
	int nButtonsMask = SensorValue[MultiPlex];
	while(!(nButtonsMask & 0x02)){
		nButtonsMask = SensorValue[MultiPlex];
		motor[Proximity] = -20;
	}
	motor[Proximity] = 20;
	//Wait
	wait1Msec(1000);
	//Stpp
	motor[Proximity] = 0;

	return SensorValue(sonar);

}

void sense(){
	if(sensorLeft() > sensorRight()){
		//Lets go left
		motor[Left ] = 20;
		motor[Right] = 20;
		wait1Msec(1500);
		motor[Right] = 0;
		motor[Left ] = 20;
		wait1Msec(2500);
		motor[Right] = 20;
		motor[Left ] = 20;
		wait1Msec(2000);
		motor[Right] = 20;
		motor[Left ] = 0;
		wait1Msec(2500);
	}
	else{
		motor[Left ] = 20;
		motor[Right] = 20;
		wait1Msec(1500);
		motor[Right] = 20;
		motor[Left ] = 0;
		wait1Msec(2500);
		motor[Right] = 20;
		motor[Left ] = 20;
		wait1Msec(2000);
		motor[Right] = 0;
		motor[Left ] = 20;
		wait1Msec(2500);
	}

}

task main ()
{
	int num = 0;
	while(num != 7){
		seek();
		sense();
		num++;
	}
	//seek();
	//sense();
}

/*
* $Id: hitechnic-irseeker-v2-test1.c 109 2012-09-25 17:10:26Z xander $
*/
