#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     driveR2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     driveL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     driveL2,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    binlift,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    release,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Motor,  mtr_S1_C4_1,    Collecter,            tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.


void foward(float mil){
	motor[driveL] = 100;
  motor[driveL2] = 100;

 	motor[driveR] = 100;
  motor[driveR2] = 100;
  wait1Msec(mil);
  motor[driveL] = 0;
  motor[driveL2] = 0;

 	motor[driveR] = 0;
  motor[driveR2] = 0;
}

void backward(float mil){
	motor[driveL] = -100;
  motor[driveL2] = -100;

 	motor[driveR] = -100;
  motor[driveR2] = -100;
  wait1Msec(mil);
  motor[driveL] = 0;
  motor[driveL2] = 0;

 	motor[driveR] = 0;
  motor[driveR2] = 0;
}
task main(){

	//1const int THRESHOLD = 5;
	getJoystickSettings (joystick);

	//bool turbo = false;

	//servo[release] = 0;
	waitForStart();   // wait for start of tele-op phase
	//servo[armRelease] = 0;
	int tick = 0;
	servo[binlift] = 110;

	foward(4000);

	servo[binlift] = 0;

	backward(1000);



}
