#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     HTIRS2,         sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     driveR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     driveR2,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     driveL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     driveL2,       tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    binlift,              tServoNone)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    release,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#ifndef max
	#define max( a, b ) ( ((a) > (b)) ? (a) : (b) )
#endif

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * $Id: hitechnic-irseeker-v2-test1.c 109 2012-09-25 17:10:26Z xander $
 */

/**
 * hitechnic-irseeker-v2.h provides an API for the HiTechnic IR Seeker V2.  This program
 * demonstrates how to use that API.
 *
 * Changelog:
 * - 0.1: Initial release
 * - 0.2: Partial rewrite by Dick Swan, waits a little longer for sensor initialisation<br>
 *        Nicer intro screen<br>
 *        Less screen flickering, only updated if there's been a change in data.
 * - 0.3: More comments
 * - 0.4: Driver renamed to HTIRS2, all functions have been renamed to HRIRS2
 *
 * Credits:
 * - Big thanks to HiTechnic for providing me with the hardware necessary to write and test this.
 *
 * License: You may use this code as you wish, provided you give credit where it's due.
 *
 * THIS CODE WILL ONLY WORK WITH ROBOTC VERSION 3.51 AND HIGHER.
 * Xander Soldaat (mightor_at_gmail.com)
 * Dick Swan
 * 06 April 2010
 * version 0.4
 */
void foward(float mil){
	motor[driveL] = 100;
  motor[driveL2] = 100;

 	motor[driveR] = 100;
  motor[driveR2] = 100;
  wait1Msec(mil);
  motor[driveL] = 0;
  motor[driveL2] = 0;

 	motor[driveR] = 0;
  motor[driveR2] = 0;
}


void backward(float mil){
	motor[driveL] = -100;
  motor[driveL2] = -100;

 	motor[driveR] = -100;
  motor[driveR2] = -100;
  wait1Msec(mil);
  motor[driveL] = 0;
  motor[driveL2] = 0;

 	motor[driveR] = 0;
  motor[driveR2] = 0;
}

void left(float mil){
	motor[driveL] = -100;
  motor[driveL2] = -100;

 	motor[driveR] = 100;
  motor[driveR2] = 100;
  wait1Msec(mil);
  motor[driveL] = 0;
  motor[driveL2] = 0;

 	motor[driveR] = 0;
  motor[driveR2] = 0;
}
void right(float mil){
	motor[driveL] = 100;
  motor[driveL2] = 100;

 	motor[driveR] = -100;
  motor[driveR2] = -100;
  wait1Msec(mil);
  motor[driveL] = 0;
  motor[driveL2] = 0;

 	motor[driveR] = 0;
  motor[driveR2] = 0;
}
#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment\Sample Programs\NXT\3rd Party Sensor Drivers\drivers\hitechnic-irseeker-v2.h"

// global variables
long nNumbCyles;
long nInits = 0;
string sTextLines[8];

// function prototypes
void displayText(int nLineNumber, const string cChar, int nValueDC, int nValueAC);
void displayInstructions();

// main task
task main ()
{
	servo[binlift] = 105;
	//foward(1000);
	//right(390);
	//left(0);
	//stage = 10;

	wait1Msec(1000);
  int last = 0;
  int stage = 1;
  int _dirDC = 0;
  int _dirAC = 0;
        int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
        int acS1, acS2, acS3, acS4, acS5 = 0;

        // the default DSP mode is 1200 Hz.
  tHTIRS2DSPMode _mode = DSP_1200;

  // show the user what to do
  displayInstructions();
  while(true)
  {
    // You can switch between the two different DSP modes by pressing the
    // orange enter button

    PlaySound(soundBeepBeep);
    while(bSoundActive)
    {}
    eraseDisplay();
    nNumbCyles = 0;
    ++nInits;
    while (true)
    {
      if ((nNumbCyles & 0x04) == 0)
        nxtDisplayTextLine(0, "Initializing...");
      else
        nxtDisplayTextLine(0, "");
      nxtDisplayCenteredBigTextLine(1, "IR Seekr");

      // set the DSP to the new mode
      if (HTIRS2setDSPMode(HTIRS2, _mode))
        break; // Sensor initialized

      ++nNumbCyles;
      PlaySound(soundShortBlip);
      nxtDisplayTextLine(4, "Inits: %d / %d", nInits, nNumbCyles);
      nxtDisplayCenteredTextLine(6, "Connect Sensor");
      nxtDisplayCenteredTextLine(7, "to Port S2");
      wait1Msec(100);
    }

    eraseDisplay();
    for (int i = 0; i < 8; ++i)
      sTextLines[i] = "";

    // display the current DSP mode
    if (_mode == DSP_1200)
      nxtDisplayTextLine(0, "      DC  1200");
    else
      nxtDisplayTextLine(0, "      DC   600");

    while (true)
    {
      ++nNumbCyles;
      if (nNxtButtonPressed == kEnterButton)
      {
        // "Enter" button has been pressed. Need to switch mode

        _mode = (_mode == DSP_1200) ?  DSP_600 : DSP_1200;
        while(nNxtButtonPressed == kEnterButton)
        {
          // Wait for "Enter" button release
        }
        break;
      }

      // Read the current non modulated signal direction
      _dirDC = HTIRS2readDCDir(HTIRS2);
      if (_dirDC < 0)
        break; // I2C read error occurred

      // read the current modulated signal direction
      _dirAC = HTIRS2readACDir(HTIRS2);
      if (_dirAC < 0)
        break; // I2C read error occurred

      // Read the individual signal strengths of the internal sensors
      // Do this for both unmodulated (DC) and modulated signals (AC)
      if (!HTIRS2readAllDCStrength(HTIRS2, dcS1, dcS2, dcS3, dcS4, dcS5))
        break; // I2C read error occurred
      if (!HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5 ))
        break; // I2C read error occurred


      //displayText(7, "Last", dcS5, acS5);
      //nxtDisplayTextLine(7, "Last: "+last);
      /*
      if(acS3 >= 50){
        int speed = 20;
        motor[DFR] = -speed;
        motor[DFL]= -speed;
        motor[DBR] = -speed;
        motor[DBL]= -speed;
      }
      else if(acS4+acS5 >= 10){
        //Right
        int speed = 20;
        motor[DFR] = speed;
        motor[DFL]= -speed;
        motor[DBR] = speed;
        motor[DBL]= -speed;
      }
      else if(acS1+acS2 >= 10){
        //Left
        int speed = 20;
        motor[DFR] = -speed;
        motor[DFL]= speed;
        motor[DBR] = -speed;
        motor[DBL]= speed;
      }
      else{
        motor[DFR] = 0;
        motor[DFL]= 0;
        motor[DBR] = 0;
        motor[DBL]= 0;
      }
      */
      while(stage == 1){
      	int acS1, acS2, acS3, acS4, acS5 = 0;
      	HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5 );

      	displayText(1, "D", _dirDC, _dirAC);
      	displayText(2, "0", dcS1, acS1);
      	displayText(3, "1", dcS2, acS2);
      	displayText(4, "2", dcS3, acS3);
      	displayText(5, "3", dcS4, acS4);
      	displayText(6, "4", dcS5, acS5);
      	displayText(7, "Last", last, acS5);
      	if(acS3 > last&&last>10){
					stage=2;
	        motor[driveL] = 0;
  				motor[driveL2] = 0;

 					motor[driveR] = 0;
  				motor[driveR2] = 0;
					wait10Msec(100);
  				backward(650);
  				wait10Msec(100);
  				left(810);

	        wait1Msec(1000);


					foward(2000);

					servo[binlift] = 0;

					backward(1000);
	      }
	      else{
	        if(acS3>last)
	        	last = acS3;
	      	int speed = 90-3*(acS2 + acS3);
	      	if (speed < 9) speed = 9;
	      	speed = -speed;
	        motor[driveL] = 100;
  				motor[driveL2] = 100;

 					motor[driveR] = 100;
  				motor[driveR2] = 100;
	        if(acS3 > 30){

	      	}
	      }
      }




    }
  }
}

// Display the instructions to the user
void displayInstructions()
{
  nxtDisplayCenteredTextLine(0, "Autonomous");
  nxtDisplayCenteredBigTextLine(1, "By Michael & Ryan");
  nxtDisplayCenteredTextLine(3, "Test 1");
  nxtDisplayCenteredTextLine(5, "Press enter to");
  nxtDisplayCenteredTextLine(6, "switch between");
  nxtDisplayCenteredTextLine(7, "600 and 1200 Hz");
  wait1Msec(2000);
}

// Minimize LCD screen flicker by only updating LCD when data has changed
void displayText(int nLineNumber, const string cChar, int nValueDC, int nValueAC)
{
  string sTemp;

  StringFormat(sTemp, "%4d  %4d", nValueDC, nValueAC);
  // Check if the new line is the same as the previous one
  // Only update screen if it's different.
  if (sTemp != sTextLines[nLineNumber])
  {
    string sTemp2;

    sTextLines[nLineNumber] = sTemp;
    StringFormat(sTemp2, "%s:  %s", cChar, sTemp);
    nxtDisplayTextLine(nLineNumber, sTemp2);
  }
}

/*
 * $Id: hitechnic-irseeker-v2-test1.c 109 2012-09-25 17:10:26Z xander $
 */
